server:
  port: 8086

spring:
  application:
    name: pet-habit-battle
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  type-aliases-package: com.pethabit.module.battle.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: tri
    port: 20886
  registry:
    address: nacos://${NACOS_SERVER:localhost:8848}
    group: DEFAULT_GROUP
  consumer:
    check: false
    retries: 1
